config/routes.rb
Rails.application.routes.draw do
  get 'products', to: 'products#index'
  post 'orders/:product_id', to: 'orders#create',as:'orders'
  get 'cart', to: 'carts#index', as: 'cart'
  devise_for :users

# resources :products, only: :index do
#   resources :orders, only: :create
# end ejemplo de ruta anidada



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product

  def self.total(user)
    total = 0
    unpayed_orders = where(user: user, payed: nil)
    unpayed_orders.each do |order|
      total += order.product.price
    end
    return total
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :orders
         has_many :products, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  def index
    @unpayed_user_orders = Order.where(user: current_user, payed: nil)
    @total = Order.total(current_user)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :authenticate_user!
  def create
    product = Product.find(params[:product_id])
    order = Order.create(user: current_user, product: product)
    redirect_to products_path, notice: 'Producto agregado correctamente'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    <% @unpayed_user_orders.each_with_index do |order, index|%>
    <tr>
      <th scope="row"><%= index + 1%></th>
      <td><%= order.product.name %></td>
      <td><%= number_to_currency order.product.price %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<p>Total:<%= number_to_currency @total %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThreeModelsThreeTables</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <div class="container">
    <%= render 'shared/flash_messages'%>
    <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<h2>Productos</h2>


<% @products.each_slice(3) do |products| %>
<div class="card-deck">
<% products.each do |product| %>
<div class="card">
  <img src="<%= product.photo %>" class="card-img-top" alt="producto">
  <div class="card-body">
    <h5 class="card-title"><%= product.name %></h5>
    <p class="card-text"><%= number_to_currency product.price %>
      <%= link_to "Comprar", orders_path(product), class: 'btn btn-warning', method: :post%></p>
    </div>
    <div class="card-footer">
      <small class="text-muted"><%= time_ago_in_words product.created_at %></small>
    </div>
  </div>
  <% end %>
</div>
<br>
<% end %>

app/views/shared/_flash_messages.html.erb
<% if notice %>
  <p class="alert alert-primary alert-dismissible fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
<%= notice %></p>
<% end%>

<% if alert %>
<p class="alert alert-danger alert-dismissible fade show" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
<%= alert %></p>
<% end%>

app/views/shared/_navbar.html.erb
<ul class="nav justify-content-end navbar-dark bg-dark">
  <% if user_signed_in?%>
      <li class="nav-item">
        <%= link_to "Cart", cart_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to "Salir", destroy_user_session_path, method: :delete, class: 'nav-link'%>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Iniciar Sesión", new_user_session_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to "Registro", new_user_registration_path, class: 'nav-link'%>
      </li>
      <% end %>
</ul>